SPRITE_IMAGE_SIZE = 128
SPRITE_SCALING = 0.6
SPRITE_SCALING_LASER = 0.8
SPRITE_SIZE = int(SPRITE_IMAGE_SIZE * SPRITE_SCALING)
ZOMBIE_SPEED = 3.5
ROBOT_SPEED = 4.5
BULLET_SPEED = 5
BULLET_DAMAGE = 10

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FIELD_LEFT_BOUNDARY = -SPRITE_SIZE * 2
FIELD_RIGHT_BOUNDARY = SPRITE_SIZE * 35
FIELD_TOP_BOUNDARY = SPRITE_SIZE * 17
FIELD_BOTTOM_BOUNDARY = -SPRITE_SIZE * 2
FIELD_WIDTH = FIELD_RIGHT_BOUNDARY - FIELD_LEFT_BOUNDARY
FIELD_HEIGHT = FIELD_TOP_BOUNDARY - FIELD_BOTTOM_BOUNDARY
SCREEN_TITLE = "It ain't much but it's an honest work"

MOVEMENT_SPEED = 5

VIEWPORT_MARGIN = 100
