SPRITE_IMAGE_SIZE = 128
SPRITE_SCALING = 0.6
SPRITE_SIZE = int(SPRITE_IMAGE_SIZE * SPRITE_SCALING)
ZOMBIE_SPEED = 3.5
ROBOT_SPEED = 4.5

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FIELD_LEFT_BOUNDARY = -SPRITE_SIZE * 2
FIELD_RIGHT_BOUNDARY = SPRITE_SIZE * 35
FIELD_TOP_BOUNDARY = SPRITE_SIZE * 17
FIELD_BOTTOM_BOUNDARY = -SPRITE_SIZE * 2
FIELD_WIDTH = FIELD_RIGHT_BOUNDARY - FIELD_LEFT_BOUNDARY
FIELD_HEIGHT = FIELD_TOP_BOUNDARY - FIELD_BOTTOM_BOUNDARY
SCREEN_TITLE = "Super gra"

MOVEMENT_SPEED = 5

VIEWPORT_MARGIN = 100
